// Generated by snapshot_schema.py; do not edit.
#pragma once
static const char *const quicklang_schema[] = {
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_ai_profiles (
  singleton_id BIGINT PRIMARY KEY,
  payload JSON NOT NULL
);)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_app_state (
  state_key VARCHAR(512) COLLATE utf8mb4_bin PRIMARY KEY,
  state_value LONGTEXT NOT NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_interpretation_chunk (
  session_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  sequence BIGINT UNSIGNED NOT NULL,
  payload LONGTEXT NOT NULL,
  PRIMARY KEY (session_id, sequence)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_interpretation_session (
  session_id VARCHAR(128) COLLATE utf8mb4_bin PRIMARY KEY,
  user_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  created_at BIGINT NOT NULL,
  payload LONGTEXT NOT NULL,
  INDEX idx_interpretation_user (user_id, created_at)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_listening (
  owner_id VARCHAR(128) NOT NULL,
  material_id VARCHAR(128) NOT NULL,
  version BIGINT UNSIGNED NOT NULL,
  payload JSON NOT NULL,
  audio MEDIUMBLOB NOT NULL,
  PRIMARY KEY (owner_id, material_id)
);)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_review_event (
  event_id VARCHAR(128) COLLATE utf8mb4_bin PRIMARY KEY,
  card_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  payload LONGTEXT NOT NULL
);)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_review_state (
  card_id VARCHAR(128) COLLATE utf8mb4_bin PRIMARY KEY,
  version BIGINT UNSIGNED NOT NULL,
  payload LONGTEXT NOT NULL
);)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_user_settings (
  user_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  setting_key VARCHAR(256) COLLATE utf8mb4_bin NOT NULL,
  setting_value JSON NOT NULL,
  PRIMARY KEY (user_id, setting_key)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.ql_word (
  spelling VARCHAR(256) COLLATE utf8mb4_bin PRIMARY KEY,
  language VARCHAR(16) NOT NULL DEFAULT 'en',
  meaning TEXT NOT NULL,
  phonetic_us VARCHAR(256),
  phonetic_uk VARCHAR(256),
  example TEXT,
  example_translation TEXT,
  example_source VARCHAR(256),
  example_license VARCHAR(64),
  example_generated BOOLEAN NOT NULL DEFAULT FALSE,
  extra_examples JSON,
  definition_source VARCHAR(256),
  source_url TEXT,
  source_revision VARCHAR(128),
  license_spdx VARCHAR(64),
  attribution LONGTEXT,
  original_spelling VARCHAR(256),
  original_meaning TEXT,
  user_modified BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  CONSTRAINT ck_word_extra_examples CHECK (
    extra_examples IS NULL
    OR JSON_TYPE(extra_examples) = 'ARRAY'
  ),
  CONSTRAINT ck_word_example_pair CHECK (
    (
      example IS NULL
      AND example_translation IS NULL
    )
    OR (
      example IS NOT NULL
      AND example_translation IS NOT NULL
    )
  ),
  CONSTRAINT ck_word_version CHECK (version >= 1)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;)QLSQL",
R"QLSQL(CREATE TABLE IF NOT EXISTS ql_ios_probe.wordbook (
  id VARCHAR(128) COLLATE utf8mb4_bin PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  words VARCHAR(256) [] NOT NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;)QLSQL"
};
