#!/usr/bin/env python3
"""Snapshot QuickLang's canonical seekdb schemas without changing its checkout."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess


def snapshot(root: Path, output: Path) -> None:
    """Write qualified test DDL and source hashes; fail on unexpected table names."""
    sources = sorted((root / 'src/schema').glob('*.sql'))
    if len(sources) != 10:
        raise ValueError('Expected the ten audited QuickLang schema files')
    entries = []
    statements = []
    for source in sources:
        data = source.read_bytes()
        ddl = data.decode()
        marker = 'CREATE TABLE IF NOT EXISTS ' + source.stem + ' ('
        if ddl.count(marker) != 1:
            raise ValueError(f'Unexpected schema: {source}')
        ddl = ddl.replace(marker, 'CREATE TABLE IF NOT EXISTS ql_ios_probe.' + source.stem + ' (', 1)
        statements.append('R"QLSQL(' + ddl.strip() + ')QLSQL"')
        entries.append({'path': str(source.relative_to(root)), 'sha256': hashlib.sha256(data).hexdigest()})
    header = '// Generated by snapshot_schema.py; do not edit.\n#pragma once\n'
    header += 'static const char *const quicklang_schema[] = {\n' + ',\n'.join(statements) + '\n};\n'
    (output / 'schema_snapshot.h').write_text(header)
    revision = subprocess.check_output(['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True).strip()
    (output / 'schema_source.json').write_text(json.dumps({'revision': revision, 'files': entries}, indent=2) + '\n')


def main() -> None:
    """Accept a local checkout and write only beside this script."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('quicklang', type=Path)
    args = parser.parse_args()
    snapshot(args.quicklang.resolve(), Path(__file__).resolve().parent)


if __name__ == '__main__':
    main()
